; 
--declare @gl_db date='2020-01-01'
--declare @gl_de date='2024-12-31'--getdate()
--declare @comp nvarchar(max)= 'STP PMZ'--'STP KZ'--'STP AMPZ'--'STP AH' --'STP MMC' 

--declare @hesab nvarchar(max)=''
--declare @cari_kod nvarchar(max)=''




--'STP QQZ'--'STP PMZ'--'STP KZ'--'STP AMPZ'--'STP AH' --'STP MMC' 
--'STP QQZ'--'STP PMZ'--'STP KZ'--'STP AMPZ'--'STP AH' --'STP MMC' 
--declare @hesab_typ nvarchar(max)='Main'

; with src as(

SELECT
 'STP MMC' comp
, EMFLINE.LOGICALREF
, u.NAME 'Yaradan Adi'
, u1.NAME 'Son Deyisdiren Adi'
, EMFICHE.CAPIBLOCK_CREADEDDATE 'Yaranma Tarixi'
, ISNULL(EMFICHE.CAPIBLOCK_MODIFIEDDATE, '') 'Son Deyisiklik Tarixi'
, EMFLINE.DATE_ 'Tarix'
, EMFLINE.DEPARTMENT 'Bölüm No'
, DEPT.NAME 'Bölüm Adý'
, EMFLINE.BRANCH 'Ýþ Yeri No'
, EMCENTER.CODE 'Masraf Kodu'
, EMCENTER.DEFINITION_ 'Masraf Adý'
, EMUHACC.CODE 'Hesab Kodu'
, EMUHACC.DEFINITION_ 'Hesab Adý'
, CASE WHEN CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) > 0 THEN    SUBSTRING(EMFLINE.LINEEXP,1,LEN(EMFLINE.LINEEXP)- CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)
			  , CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 1)+ 2 ) + SUBSTRING(EMFLINE.LINEEXP, LEN(EMFLINE.LINEEXP) - CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 2,
                CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)))         ELSE EMFLINE.LINEEXP   END 'Açýqlama'
, EMFICHE.FICHENO 'Mahsub No'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.DEBIT) 'Debit'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.CREDIT) 'Kredit'
, EMFICHE.MODULENR 'Kaynak Fiþ Türü'
, EMFLINE.CLCODE 'Cari Kod'
, EMFLINE.CLDEF 'Cari Ad'
, EMFLINE.CROSSCODE 'qarsi hesab kod'
, EMUHACC1.DEFINITION_ 'qarsi hesab ad'
, div.NAME is_yeri
FROM TGR3.dbo.LG_001_01_EMFLINE EMFLINE WITH(NOLOCK) 
    left JOIN TGR3.dbo.LG_001_01_EMFICHE EMFICHE WITH(NOLOCK)  ON EMFICHE.LOGICALREF = EMFLINE.ACCFICHEREF
    LEFT JOIN TGR3.dbo.LG_001_EMUHACC EMUHACC   WITH(NOLOCK)   ON EMFLINE.ACCOUNTREF = EMUHACC.LOGICALREF
    LEFT JOIN TGR3.dbo.LG_001_EMUHACC EMUHACC1  WITH(NOLOCK)    on EMFLINE.CROSSCODE = EMUHACC1.CODE
    left join TGR3.dbo.L_CAPIUSER u   WITH(NOLOCK)    on u.NR = EMFICHE.CAPIBLOCK_CREATEDBY
    left join TGR3.dbo.L_CAPIUSER u1    WITH(NOLOCK)   on u1.NR = EMFICHE.CAPIBLOCK_MODIFIEDBY
    LEFT JOIN TGR3.dbo.L_CAPIDEPT DEPT   WITH(NOLOCK)   ON DEPT.NR = EMFLINE.DEPARTMENT       AND DEPT.FIRMNR = 1
    LEFT JOIN TGR3.dbo.LG_001_EMCENTER EMCENTER  WITH(NOLOCK)    ON EMCENTER.LOGICALREF = EMFLINE.CENTERREF
	left join TGR3.dbo.[L_CAPIDIV] div WITH(NOLOCK) on div.NR=  EMFLINE.BRANCH and div.FIRMNR=1
WHERE EMFLINE.DATE_ >= @gl_db     AND EMFLINE.DATE_ <= @gl_de   and EMFLINE.CANCELLED = 0
and @comp in ('STP MMC')


union all


SELECT
 'STP AH' comp
, EMFLINE.LOGICALREF
, u.NAME 'Yaradan Adi'
, u1.NAME 'Son Deyisdiren Adi'
, EMFICHE.CAPIBLOCK_CREADEDDATE 'Yaranma Tarixi'
, ISNULL(EMFICHE.CAPIBLOCK_MODIFIEDDATE, '') 'Son Deyisiklik Tarixi'
, EMFLINE.DATE_ 'Tarix'
, EMFLINE.DEPARTMENT 'Bölüm No'
, DEPT.NAME 'Bölüm Adý'
, EMFLINE.BRANCH 'Ýþ Yeri No'
, EMCENTER.CODE 'Masraf Kodu'
, EMCENTER.DEFINITION_ 'Masraf Adý'
, EMUHACC.CODE 'Hesab Kodu'
, EMUHACC.DEFINITION_ 'Hesab Adý'
, CASE WHEN CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) > 0 THEN    SUBSTRING(EMFLINE.LINEEXP,1,LEN(EMFLINE.LINEEXP)- CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)
			  , CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 1)+ 2 ) + SUBSTRING(EMFLINE.LINEEXP, LEN(EMFLINE.LINEEXP) - CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 2,
                CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)))         ELSE EMFLINE.LINEEXP   END 'Açýqlama'
, EMFICHE.FICHENO 'Mahsub No'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.DEBIT) 'Debit'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.CREDIT) 'Kredit'
, EMFICHE.MODULENR 'Kaynak Fiþ Türü'
, EMFLINE.CLCODE 'Cari Kod'
, EMFLINE.CLDEF 'Cari Ad'
, EMFLINE.CROSSCODE 'qarsi hesab kod'
, EMUHACC1.DEFINITION_ 'qarsi hesab ad'
, div.NAME is_yeri
FROM          TGR3_AH.dbo.LG_001_01_EMFLINE EMFLINE WITH(NOLOCK) 
    left JOIN TGR3_AH.dbo.LG_001_01_EMFICHE EMFICHE WITH(NOLOCK)  ON EMFICHE.LOGICALREF = EMFLINE.ACCFICHEREF
    LEFT JOIN TGR3_AH.dbo.LG_001_EMUHACC EMUHACC   WITH(NOLOCK)   ON EMFLINE.ACCOUNTREF = EMUHACC.LOGICALREF
    LEFT JOIN TGR3_AH.dbo.LG_001_EMUHACC EMUHACC1  WITH(NOLOCK)    on EMFLINE.CROSSCODE = EMUHACC1.CODE
    left join TGR3_AH.dbo.L_CAPIUSER u   WITH(NOLOCK)    on u.NR = EMFICHE.CAPIBLOCK_CREATEDBY
    left join TGR3_AH.dbo.L_CAPIUSER u1    WITH(NOLOCK)   on u1.NR = EMFICHE.CAPIBLOCK_MODIFIEDBY
    LEFT JOIN TGR3_AH.dbo.L_CAPIDEPT DEPT   WITH(NOLOCK)   ON DEPT.NR = EMFLINE.DEPARTMENT       AND DEPT.FIRMNR = 1
    LEFT JOIN TGR3_AH.dbo.LG_001_EMCENTER EMCENTER  WITH(NOLOCK)    ON EMCENTER.LOGICALREF = EMFLINE.CENTERREF
	left join TGR3_AH.dbo.[L_CAPIDIV] div WITH(NOLOCK) on div.NR=  EMFLINE.BRANCH and div.FIRMNR=1
WHERE EMFLINE.DATE_ >= @gl_db     AND EMFLINE.DATE_ <= @gl_de   and EMFLINE.CANCELLED = 0
and @comp in ('STP AH')


union all


SELECT
 'STP AMPZ' comp
, EMFLINE.LOGICALREF
, u.NAME 'Yaradan Adi'
, u1.NAME 'Son Deyisdiren Adi'
, EMFICHE.CAPIBLOCK_CREADEDDATE 'Yaranma Tarixi'
, ISNULL(EMFICHE.CAPIBLOCK_MODIFIEDDATE, '') 'Son Deyisiklik Tarixi'
, EMFLINE.DATE_ 'Tarix'
, EMFLINE.DEPARTMENT 'Bölüm No'
, DEPT.NAME 'Bölüm Adý'
, EMFLINE.BRANCH 'Ýþ Yeri No'
, EMCENTER.CODE 'Masraf Kodu'
, EMCENTER.DEFINITION_ 'Masraf Adý'
, EMUHACC.CODE 'Hesab Kodu'
, EMUHACC.DEFINITION_ 'Hesab Adý'
, CASE WHEN CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) > 0 THEN    SUBSTRING(EMFLINE.LINEEXP,1,LEN(EMFLINE.LINEEXP)- CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)
			  , CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 1)+ 2 ) + SUBSTRING(EMFLINE.LINEEXP, LEN(EMFLINE.LINEEXP) - CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 2,
                CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)))         ELSE EMFLINE.LINEEXP   END 'Açýqlama'
, EMFICHE.FICHENO 'Mahsub No'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.DEBIT) 'Debit'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.CREDIT) 'Kredit'
, EMFICHE.MODULENR 'Kaynak Fiþ Türü'
, EMFLINE.CLCODE 'Cari Kod'
, EMFLINE.CLDEF 'Cari Ad'
, EMFLINE.CROSSCODE 'qarsi hesab kod'
, EMUHACC1.DEFINITION_ 'qarsi hesab ad'
, div.NAME is_yeri
FROM          TGR3_AMPZ.dbo.LG_001_01_EMFLINE EMFLINE WITH(NOLOCK) 
    left JOIN TGR3_AMPZ.dbo.LG_001_01_EMFICHE EMFICHE WITH(NOLOCK)  ON EMFICHE.LOGICALREF = EMFLINE.ACCFICHEREF
    LEFT JOIN TGR3_AMPZ.dbo.LG_001_EMUHACC EMUHACC   WITH(NOLOCK)   ON EMFLINE.ACCOUNTREF = EMUHACC.LOGICALREF
    LEFT JOIN TGR3_AMPZ.dbo.LG_001_EMUHACC EMUHACC1  WITH(NOLOCK)    on EMFLINE.CROSSCODE = EMUHACC1.CODE
    left join TGR3_AMPZ.dbo.L_CAPIUSER u   WITH(NOLOCK)    on u.NR = EMFICHE.CAPIBLOCK_CREATEDBY
    left join TGR3_AMPZ.dbo.L_CAPIUSER u1    WITH(NOLOCK)   on u1.NR = EMFICHE.CAPIBLOCK_MODIFIEDBY
    LEFT JOIN TGR3_AMPZ.dbo.L_CAPIDEPT DEPT   WITH(NOLOCK)   ON DEPT.NR = EMFLINE.DEPARTMENT       AND DEPT.FIRMNR = 1
    LEFT JOIN TGR3_AMPZ.dbo.LG_001_EMCENTER EMCENTER  WITH(NOLOCK)    ON EMCENTER.LOGICALREF = EMFLINE.CENTERREF
	left join TGR3_AMPZ.dbo.[L_CAPIDIV] div WITH(NOLOCK) on div.NR=  EMFLINE.BRANCH and div.FIRMNR=1
WHERE EMFLINE.DATE_ >= @gl_db     AND EMFLINE.DATE_ <= @gl_de   and EMFLINE.CANCELLED = 0
and @comp in ('STP AMPZ')



union all


SELECT
 'STP KZ' comp
, EMFLINE.LOGICALREF
, u.NAME 'Yaradan Adi'
, u1.NAME 'Son Deyisdiren Adi'
, EMFICHE.CAPIBLOCK_CREADEDDATE 'Yaranma Tarixi'
, ISNULL(EMFICHE.CAPIBLOCK_MODIFIEDDATE, '') 'Son Deyisiklik Tarixi'
, EMFLINE.DATE_ 'Tarix'
, EMFLINE.DEPARTMENT 'Bölüm No'
, DEPT.NAME 'Bölüm Adý'
, EMFLINE.BRANCH 'Ýþ Yeri No'
, EMCENTER.CODE 'Masraf Kodu'
, EMCENTER.DEFINITION_ 'Masraf Adý'
, EMUHACC.CODE 'Hesab Kodu'
, EMUHACC.DEFINITION_ 'Hesab Adý'
, CASE WHEN CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) > 0 THEN    SUBSTRING(EMFLINE.LINEEXP,1,LEN(EMFLINE.LINEEXP)- CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)
			  , CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 1)+ 2 ) + SUBSTRING(EMFLINE.LINEEXP, LEN(EMFLINE.LINEEXP) - CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 2,
                CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)))         ELSE EMFLINE.LINEEXP   END 'Açýqlama'
, EMFICHE.FICHENO 'Mahsub No'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.DEBIT) 'Debit'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.CREDIT) 'Kredit'
, EMFICHE.MODULENR 'Kaynak Fiþ Türü'
, EMFLINE.CLCODE 'Cari Kod'
, EMFLINE.CLDEF 'Cari Ad'
, EMFLINE.CROSSCODE 'qarsi hesab kod'
, EMUHACC1.DEFINITION_ 'qarsi hesab ad'
, div.NAME is_yeri
FROM          TGR3_KZ.dbo.LG_001_01_EMFLINE EMFLINE WITH(NOLOCK) 
    left JOIN TGR3_KZ.dbo.LG_001_01_EMFICHE EMFICHE WITH(NOLOCK)  ON EMFICHE.LOGICALREF = EMFLINE.ACCFICHEREF
    LEFT JOIN TGR3_KZ.dbo.LG_001_EMUHACC EMUHACC   WITH(NOLOCK)   ON EMFLINE.ACCOUNTREF = EMUHACC.LOGICALREF
    LEFT JOIN TGR3_KZ.dbo.LG_001_EMUHACC EMUHACC1  WITH(NOLOCK)    on EMFLINE.CROSSCODE = EMUHACC1.CODE
    left join TGR3_KZ.dbo.L_CAPIUSER u   WITH(NOLOCK)    on u.NR = EMFICHE.CAPIBLOCK_CREATEDBY
    left join TGR3_KZ.dbo.L_CAPIUSER u1    WITH(NOLOCK)   on u1.NR = EMFICHE.CAPIBLOCK_MODIFIEDBY
    LEFT JOIN TGR3_KZ.dbo.L_CAPIDEPT DEPT   WITH(NOLOCK)   ON DEPT.NR = EMFLINE.DEPARTMENT       AND DEPT.FIRMNR = 1
    LEFT JOIN TGR3_KZ.dbo.LG_001_EMCENTER EMCENTER  WITH(NOLOCK)    ON EMCENTER.LOGICALREF = EMFLINE.CENTERREF
	left join TGR3_KZ.dbo.[L_CAPIDIV] div WITH(NOLOCK) on div.NR=  EMFLINE.BRANCH and div.FIRMNR=1
WHERE EMFLINE.DATE_ >= @gl_db     AND EMFLINE.DATE_ <= @gl_de   and EMFLINE.CANCELLED = 0
and @comp in ('STP KZ')
 

 
union all


SELECT
 'STP PMZ' comp
, EMFLINE.LOGICALREF
, u.NAME 'Yaradan Adi'
, u1.NAME 'Son Deyisdiren Adi'
, EMFICHE.CAPIBLOCK_CREADEDDATE 'Yaranma Tarixi'
, ISNULL(EMFICHE.CAPIBLOCK_MODIFIEDDATE, '') 'Son Deyisiklik Tarixi'
, EMFLINE.DATE_ 'Tarix'
, EMFLINE.DEPARTMENT 'Bölüm No'
, DEPT.NAME 'Bölüm Adý'
, EMFLINE.BRANCH 'Ýþ Yeri No'
, EMCENTER.CODE 'Masraf Kodu'
, EMCENTER.DEFINITION_ 'Masraf Adý'
, EMUHACC.CODE 'Hesab Kodu'
, EMUHACC.DEFINITION_ 'Hesab Adý'
, CASE WHEN CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) > 0 THEN    SUBSTRING(EMFLINE.LINEEXP,1,LEN(EMFLINE.LINEEXP)- CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)
			  , CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 1)+ 2 ) + SUBSTRING(EMFLINE.LINEEXP, LEN(EMFLINE.LINEEXP) - CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 2,
                CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)))         ELSE EMFLINE.LINEEXP   END 'Açýqlama'
, EMFICHE.FICHENO 'Mahsub No'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.DEBIT) 'Debit'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.CREDIT) 'Kredit'
, EMFICHE.MODULENR 'Kaynak Fiþ Türü'
, EMFLINE.CLCODE 'Cari Kod'
, EMFLINE.CLDEF 'Cari Ad'
, EMFLINE.CROSSCODE 'qarsi hesab kod'
, EMUHACC1.DEFINITION_ 'qarsi hesab ad'
, div.NAME is_yeri
FROM          TGR3_PMZ.dbo.LG_001_01_EMFLINE EMFLINE WITH(NOLOCK) 
    left JOIN TGR3_PMZ.dbo.LG_001_01_EMFICHE EMFICHE WITH(NOLOCK)  ON EMFICHE.LOGICALREF = EMFLINE.ACCFICHEREF
    LEFT JOIN TGR3_PMZ.dbo.LG_001_EMUHACC EMUHACC   WITH(NOLOCK)   ON EMFLINE.ACCOUNTREF = EMUHACC.LOGICALREF
    LEFT JOIN TGR3_PMZ.dbo.LG_001_EMUHACC EMUHACC1  WITH(NOLOCK)    on EMFLINE.CROSSCODE = EMUHACC1.CODE
    left join TGR3_PMZ.dbo.L_CAPIUSER u   WITH(NOLOCK)    on u.NR = EMFICHE.CAPIBLOCK_CREATEDBY
    left join TGR3_PMZ.dbo.L_CAPIUSER u1    WITH(NOLOCK)   on u1.NR = EMFICHE.CAPIBLOCK_MODIFIEDBY
    LEFT JOIN TGR3_PMZ.dbo.L_CAPIDEPT DEPT   WITH(NOLOCK)   ON DEPT.NR = EMFLINE.DEPARTMENT       AND DEPT.FIRMNR = 1
    LEFT JOIN TGR3_PMZ.dbo.LG_001_EMCENTER EMCENTER  WITH(NOLOCK)    ON EMCENTER.LOGICALREF = EMFLINE.CENTERREF
	left join TGR3_PMZ.dbo.[L_CAPIDIV] div WITH(NOLOCK) on div.NR=  EMFLINE.BRANCH and div.FIRMNR=1
WHERE EMFLINE.DATE_ >= @gl_db     AND EMFLINE.DATE_ <= @gl_de   and EMFLINE.CANCELLED = 0
and @comp in ('STP PMZ')



union all


SELECT
 'STP QQZ' comp 
, EMFLINE.LOGICALREF
, u.NAME 'Yaradan Adi'
, u1.NAME 'Son Deyisdiren Adi'
, EMFICHE.CAPIBLOCK_CREADEDDATE 'Yaranma Tarixi'
, ISNULL(EMFICHE.CAPIBLOCK_MODIFIEDDATE, '') 'Son Deyisiklik Tarixi'
, EMFLINE.DATE_ 'Tarix'
, EMFLINE.DEPARTMENT 'Bölüm No'
, DEPT.NAME 'Bölüm Adý'
, EMFLINE.BRANCH 'Ýþ Yeri No'
, EMCENTER.CODE 'Masraf Kodu'
, EMCENTER.DEFINITION_ 'Masraf Adý'
, EMUHACC.CODE 'Hesab Kodu'
, EMUHACC.DEFINITION_ 'Hesab Adý'
, CASE WHEN CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) > 0 THEN    SUBSTRING(EMFLINE.LINEEXP,1,LEN(EMFLINE.LINEEXP)- CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)
			  , CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 1)+ 2 ) + SUBSTRING(EMFLINE.LINEEXP, LEN(EMFLINE.LINEEXP) - CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)) + 2,
                CHARINDEX(',', REVERSE(EMFLINE.LINEEXP)))         ELSE EMFLINE.LINEEXP   END 'Açýqlama'
, EMFICHE.FICHENO 'Mahsub No'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.DEBIT) 'Debit'
, iif(EMFICHE.CAPIBLOCK_CREATEDBY=1 and EMFICHE.TRCODE in (1,7) , 0, EMFLINE.CREDIT) 'Kredit'
, EMFICHE.MODULENR 'Kaynak Fiþ Türü'
, EMFLINE.CLCODE 'Cari Kod'
, EMFLINE.CLDEF 'Cari Ad'
, EMFLINE.CROSSCODE 'qarsi hesab kod'
, EMUHACC1.DEFINITION_ 'qarsi hesab ad'
, div.NAME is_yeri
FROM          TGR3_QQZ.dbo.LG_001_01_EMFLINE EMFLINE WITH(NOLOCK) 
    left JOIN TGR3_QQZ.dbo.LG_001_01_EMFICHE EMFICHE WITH(NOLOCK)  ON EMFICHE.LOGICALREF = EMFLINE.ACCFICHEREF
    LEFT JOIN TGR3_QQZ.dbo.LG_001_EMUHACC EMUHACC   WITH(NOLOCK)   ON EMFLINE.ACCOUNTREF = EMUHACC.LOGICALREF
    LEFT JOIN TGR3_QQZ.dbo.LG_001_EMUHACC EMUHACC1  WITH(NOLOCK)    on EMFLINE.CROSSCODE = EMUHACC1.CODE
    left join TGR3_QQZ.dbo.L_CAPIUSER u   WITH(NOLOCK)    on u.NR = EMFICHE.CAPIBLOCK_CREATEDBY
    left join TGR3_QQZ.dbo.L_CAPIUSER u1    WITH(NOLOCK)   on u1.NR = EMFICHE.CAPIBLOCK_MODIFIEDBY
    LEFT JOIN TGR3_QQZ.dbo.L_CAPIDEPT DEPT   WITH(NOLOCK)   ON DEPT.NR = EMFLINE.DEPARTMENT       AND DEPT.FIRMNR = 1
    LEFT JOIN TGR3_QQZ.dbo.LG_001_EMCENTER EMCENTER  WITH(NOLOCK)    ON EMCENTER.LOGICALREF = EMFLINE.CENTERREF
	left join TGR3_QQZ.dbo.[L_CAPIDIV] div WITH(NOLOCK) on div.NR=  EMFLINE.BRANCH and div.FIRMNR=1
WHERE EMFLINE.DATE_ >= @gl_db     AND EMFLINE.DATE_ <= @gl_de   and EMFLINE.CANCELLED = 0
and @comp in ('STP QQZ')
)
 
 

 select *
 from src z
 where z.[Hesab Kodu]=@hesab and z.[Cari Kod]=@cari_kod